config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'visitors#home'

  resources :orders
  resources :products
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/order.rb
class Order < ApplicationRecord
end

app/models/product.rb
class Product < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  protect_from_forgery with: :exception
  before_action :authenticate_user!

  def new
    @order = Order.new(product_id: params[:product])
  end

  def create
    @order = Order.new(order_params)

    if !@order.save
      render 'error'
    else
      OrderMailer.with(order: @order).new_order_email.deliver_later
    end
  end

  private

    def order_params
      params.require(:order).permit(
        :quantity, :product_id, :customer_name, :shipping_address)
    end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, only: [:show, :edit, :update, :destroy]

  # GET /products
  # GET /products.json
  def index
    @products = Product.all
  end

  # GET /products/1
  # GET /products/1.json
  def show
  end

  # GET /products/new
  def new
    @product = Product.new
  end

  # GET /products/1/edit
  def edit
  end

  # POST /products
  # POST /products.json
  def create
    @product = Product.new(product_params)

    respond_to do |format|
      if @product.save
        format.html { redirect_to @product, notice: 'Product was successfully created.' }
        format.json { render :show, status: :created, location: @product }
      else
        format.html { render :new }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /products/1
  # PATCH/PUT /products/1.json
  def update
    respond_to do |format|
      if @product.update(product_params)
        format.html { redirect_to @product, notice: 'Product was successfully updated.' }
        format.json { render :show, status: :ok, location: @product }
      else
        format.html { render :edit }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1
  # DELETE /products/1.json
  def destroy
    @product.destroy
    respond_to do |format|
      format.html { redirect_to products_url, notice: 'Product was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product
      @product = Product.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def product_params
      params.require(:product).permit(:description, :price, :imagePath, :discount)
    end
end

app/controllers/visitors_controller.rb
class VisitorsController < ApplicationController

  def home
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/visitors_helper.rb
module VisitorsHelper
end

app/views/layouts/_footer.html.slim
footer.footer
  small
    | The 
    = link_to "Minions Store ", root_path
    | by 
    a<>[href="http://github.com/luislhl"]
      | Luis Helder

app/views/layouts/_header.html.slim
header.navbar.navbar-fixed-top.navbar-inverse
  div.container
    = link_to "Minions Store", root_path, :class => 'logo'
    nav
      ul.nav.navbar-nav.navbar-right
        li = link_to "Home", root_path
        -if user_signed_in?
          | Logged in as
          strong = current_user.email
          li = link_to 'Edit profile', edit_user_registration_path, :class => 'navbar-link'
          li = link_to "Logout", destroy_user_session_path, method: :delete, :class => 'navbar-link'
        -else
          li = link_to "Sign up", new_user_registration_path, :class => 'navbar-link'
          li = link_to "Login", new_user_session_path, :class => 'navbar-link'

app/views/layouts/application.html.slim
doctype html
html
  head
    title #{yield(:title)} | Minions Store
    = csrf_meta_tags
    = csp_meta_tag

    = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'

  body
    = render 'layouts/header'
    div.container
      -if notice
        p.alert.alert-success = notice
      -if alert
        p.alert.alert-danger = alert
      = yield
      = render 'layouts/footer'

app/views/orders/create.html.slim
-provide(:title, "Form")

h1 Order created successfully! 

table
  tbody
    tr
      td Order Number
      td = @order.id
    tr
      td Product
      td = @order.product_id
    tr
      td Quantity
      td = @order.quantity
    tr
      td Customer Name
      td = @order.customer_name
    tr
      td Shipping Address 
      td = @order.shipping_address

app/views/orders/error.html.slim
-provide(:title, "Order")

h1 Error when creating order :(

app/views/orders/new.html.slim
-provide(:title, "Form")

h1 Create new order 

= semantic_form_for @order do |f|
  = f.inputs do
    = f.input :quantity, :label => "Quantity", :required => true
    = f.input :customer_name, :label => "Your Name"
    = f.input :shipping_address, :label => "Shipping Address", :required => true
    = f.input :product_id, :as => :hidden, :value => params[:product_id]
  = f.actions :submit

app/views/products/_form.html.slim
= form_for @product do |f|
  - if @product.errors.any?
    #error_explanation
      h2 = "#{pluralize(@product.errors.count, "error")} prohibited this product from being saved:"
      ul
        - @product.errors.full_messages.each do |message|
          li = message

  .field
    = f.label :description
    = f.text_field :description
  .field
    = f.label :price
    = f.number_field :price
  .field
    = f.label :imagePath
    = f.text_field :imagePath
  .field
    = f.label :discount
    = f.number_field :discount
  .actions = f.submit

app/views/products/_product_card.html.slim
.thumb-wrapper
  - if product.imagePath
    .img-box
      = image_tag product.imagePath, class: 'img-responsive img-fluid'
  .thumb-content
    h4 = product.description 
    p.item-price
      strike = number_to_currency(product.price, :unit => "$")
      span = number_to_currency(product.price - product.discount, :unit => "$")
    = link_to "Buy it now!", new_order_path(:product => product), class: "btn btn-primary"

app/views/products/edit.html.slim
h1 Editing product

== render 'form'

=> link_to 'Show', @product
'|
=< link_to 'Back', products_path

app/views/products/index.html.slim
h1 Minions Available 

/ table
/   thead
/     tr
/       th Description
/       th Price
/       th Imagepath
/       th Discount
/       th
/       th
/       th

/   tbody
/     - @products.each do |product|
/       tr
/         td = product.description
/         td = product.price
/         td = product.imagePath
/         td = product.discount
/         td = link_to 'Show', product
/         td = link_to 'Edit', edit_product_path(product)
/         td = link_to 'Destroy', product, data: { confirm: 'Are you sure?' }, method: :delete

/ br

/ = link_to 'New Product', new_product_path


.container
  .row
    .col-md-12
      .carousel.slide data-interval="0" data-ride="carousel" 
        /! Wrapper for carousel items
        .carousel-inner
          .item.carousel-item.active
            .row
              - @products.each do |product|
                  .col-sm-3
                    = render partial: "product_card", locals: {product: product}

app/views/products/new.html.slim
h1 New product

== render 'form'

= link_to 'Back', products_path

app/views/products/show.html.slim
p#notice = notice

p
  strong Description:
  = @product.description
p
  strong Price:
  = @product.price
p
  strong Imagepath:
  = @product.imagePath
p
  strong Discount:
  = @product.discount

=> link_to 'Edit', edit_product_path(@product)
'|
=< link_to 'Back', products_path

app/views/users/new.html.slim
-provide(:title, "Signup")

h1 Users#new
p Find me in app/views/users/new.html.slim

app/views/visitors/home.html.slim
-provide(:title,"Home")

div.center.jumbotron
  h1 Welcome to the Minions Store

  h2
    | Here you can buy gorgeous Minion dolls 

  -if user_signed_in?
    = link_to "Check available Minions!", products_path, class: "btn btn-lg btn-primary"
  -else
    = link_to "Sign up now!", new_user_registration_path, class: "btn btn-lg btn-primary"